# Generated by Django 2.2.1 on 2019-05-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.IntegerField(choices=[(1, 'Basic'), (2, 'Flex'), (3, 'Comfort'), (4, 'Business'), (5, 'Luxury')])),
                ('brand', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('fuel', models.IntegerField(choices=[(1, 'Benzyna'), (2, 'Benzyna + LPG'), (3, 'Diesel')])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('second_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=128)),
                ('year_of_birth', models.IntegerField()),
                ('card_number', models.BigIntegerField()),
            ],
        ),
    ]
