# Generated by Django 2.2.1 on 2019-05-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.IntegerField(choices=[(1, 'Basic'), (2, 'Flex'), (3, 'Comfort'), (4, 'Business'), (5, 'Luxury')])),
                ('brand', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('fuel', models.IntegerField(choices=[(1, 'Benzyna'), (2, 'Benzyna + LPG'), (3, 'Diesel')])),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
